# permissions for end users to view nginxwebservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxwebserver-viewer-role
rules:
- apiGroups:
  - nginx.eden.koveshi
  resources:
  - nginxwebservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx.eden.koveshi
  resources:
  - nginxwebservers/status
  verbs:
  - get
