# permissions for end users to edit nginxwebservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginxwebserver-editor-role
rules:
- apiGroups:
  - nginx.eden.koveshi
  resources:
  - nginxwebservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx.eden.koveshi
  resources:
  - nginxwebservers/status
  verbs:
  - get
