apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-operator
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      containers:
      - name: nginx-operator
        image: edenkoveshi/nginx-operator:latest
        ports:
        - containerPort: 8443

---
apiVersion: nginx.eden.koveshi/v1alpha1
kind: NGINXWebServer
metadata:
  name: my-test
spec:
  replicas: 2
  image: docker.io/library/nginx:latest
  diskSize: 8